[metadata]
name = range42
version = 0.1.0
description = Range42 infrastructure CLI
author = t0kubetsu
author_email = alexis.danjon@nc3.lu
license = AGPLv3
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/range42/range42
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: GNU Affero General Public License v3
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3 :: Only
    Topic :: Education
    Topic :: Games/Entertainment :: Simulation
    Intended Audience :: Developers
    Intended Audience :: System Administrators
    Intended Audience :: Information Technology
    Environment :: Console

[options]
packages = find:
python_requires = >=3.10
include_package_data = true
install_requires =
    requests
    jinja2
    ansible

[options.package_data]
range42 = 
    templates/*.j2

[options.entry_points]
console_scripts =
    range42 = range42.cli:main