---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: upload scenario inventory
  block:
    - name: upload scenario inventory - create inventory directory
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/inventory"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"
      become: true

    #### #### #### #### #### #### #### #### ####
    #### #### #### #### #### #### #### #### ####

    - name: upload scenario inventory - copy inventory file
      ansible.builtin.template:
        src: inventory.demo_lab.j2
        dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/inventory/inventory_default.yml"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"

    # - name: upload scenario inventory - copy inventory file - TO DELETE # TO DELETE IN NEXT COMMITS
    #   ansible.builtin.template:
    #     src: inventory.demo_lab.j2
    #     dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/inventory/off_cr_42.yml"
    #     owner: "{{ DEPLOYER_CLI_USER }}"
    #     group: "{{ DEPLOYER_CLI_USER }}"
    #     mode: "0600"
