- name: "Check if we should generate VM passwords"
  ansible.builtin.set_fact:
    deployer_generate_vm_passwords: "{{ context_auto_deployer_generate_vm_passwords | default('YES') | upper == 'YES' }}"

- name: "Generate VM passwords"
  ansible.builtin.set_fact:
    deployer_infrastructure_default_admin_vm_ci_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}
    deployer_infrastructure_default_trainee_vm_ci_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}
    deployer_infrastructure_wazuh_admin_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}
  when: deployer_generate_vm_passwords

- name: "Use existing passwords from config if generation disabled"
  ansible.builtin.set_fact:
    deployer_infrastructure_default_admin_vm_ci_password: "{{ default_admin_vm_ci_password }}"
    deployer_infrastructure_default_trainee_vm_ci_password: "{{ default_trainee_vm_ci_password }}"
    deployer_infrastructure_wazuh_admin_password: "{{ WAZUH_PASSWORD }}"
  when: not deployer_generate_vm_passwords

- name: "Generate other passwords"
  ansible.builtin.set_fact:
    deployer_alice_user_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}
    deployer_bob_user_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}
    deployer_jump_password: >-
      {{ jump_password | default(
           lookup(
             'ansible.builtin.password',
             '/dev/null',
             chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
             length=24
           ),
           true
         ) }}
    deployer_vault_password: >-
      {{ lookup(
           'ansible.builtin.password',
           '/dev/null',
           chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
           length=24
         ) }}

- name: "Printing generated passwords"
  ansible.builtin.debug:
    msg:
      - "Admin VM password: {{ deployer_infrastructure_default_admin_vm_ci_password }}"
      - "Trainee VM password: {{ deployer_infrastructure_default_trainee_vm_ci_password }}"
      - "Wazuh password: {{ deployer_infrastructure_wazuh_admin_password }}"
      - "Alice user password: {{ deployer_alice_user_password }}"
      - "Bob user password: {{ deployer_bob_user_password }}"
      - "Jump user password: {{ deployer_jump_password }}"
      - "Vault password: {{ deployer_vault_password }}"
