- name: Create user
  ansible.builtin.command:
    cmd: "pveum user add {{ deployer_proxmox_api_user }}@pam"
  register: deployer_user_creation
  delegate_to: proxmox
  failed_when:
    - deployer_user_creation.rc != 0
    - "'already exists' not in deployer_user_creation.stderr"
  changed_when:
    - deployer_user_creation.rc == 0

- name: Ensure token ID is set
  ansible.builtin.set_fact:
    deployer_proxmox_api_token_id: >-
      {{ proxmox_api_token_id
         if proxmox_api_token_id | default('') | length > 0
         else lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase','ascii_uppercase'], length=5) }}

- name: Generating Proxmox API credentials
  ansible.builtin.command:
    cmd: "pveum user token add {{ deployer_proxmox_api_user }}@pam {{ deployer_proxmox_api_token_id }} --privsep 0 --output-format json"
  register: deployer_token_creation
  delegate_to: proxmox
  failed_when:
    - deployer_token_creation.rc != 0
    - "'already exists' not in deployer_token_creation.stderr"
  changed_when:
    - deployer_token_creation.rc == 0

- name: Set Proxmox API token secret # noqa: no-handler
  ansible.builtin.set_fact:
    deployer_proxmox_api_token_secret: >-
      {{ deployer_token_creation.stdout | from_json | json_query('value') }}
  when: deployer_token_creation.changed

- name: Show token and token secret
  ansible.builtin.debug:
    msg: "token_id = {{ deployer_proxmox_api_token_id }} token_secret = {{ deployer_proxmox_api_token_secret }}"

- name: Check if user is already Administrator
  ansible.builtin.command: pveum acl list
  delegate_to: proxmox
  register: deployer_proxmox_acl_list
  changed_when: false

- name: Set user as Administrator if not already
  ansible.builtin.command: >
    pveum acl modify / -user {{ deployer_proxmox_api_user }}@pam -role Administrator
  delegate_to: proxmox
  when: >
    deployer_proxmox_acl_list.stdout_lines
    | select("search", "Administrator.*" + deployer_proxmox_api_user + "@pam")
    | list
    | length == 0
  changed_when: true

- name: Test Proxmox API token
  ansible.builtin.uri:
    url: "https://{{ deployer_proxmox_api_host }}/api2/json/nodes"
    method: GET
    headers:
      Authorization: >-
        PVEAPIToken={{ deployer_proxmox_api_user }}@pam!{{ deployer_proxmox_api_token_id }}={{ deployer_proxmox_api_token_secret }}
    validate_certs: false
    return_content: true
    status_code: 200
    timeout: 3
