---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: configure ssh client - "{{ DEPLOYER_CLI_USER }}"
  # become: true
  # become_user: "{{ DEPLOYER_CLI_USER }}"

  block:
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
    # check/create directories in /home/{{DEPLOYER_CLI_USER}}/.ssh/
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    - name: configure ssh client - check /home/{{DEPLOYER_CLI_USER}}/.ssh dir exists
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_SSH_CONFIG_DIR }}"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"

    - name: configure ssh client - check /home/{{DEPLOYER_CLI_USER}}/.ssh/config file exists
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_SSH_CONFIG_DEFAULT_FILE }}"
        state: touch
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"

    - name: configure ssh client - check /home/{{DEPLOYER_CLI_USER}}/.ssh/authorized_keys file exists
      ansible.builtin.file:
        path: "/home/{{ DEPLOYER_CLI_USER }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"

    ####
    ####
    ####

    - name: configure ssh client - check {{ DEPLOYER_CLI__DST_SSH_KEYS_BACKEND_DEST_DIR }} dir exists
      #  check /home/{{DEPLOYER_CLI_USER}}/.ssh/backend_keys dir exists
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_SSH_KEYS_BACKEND_DEST_DIR }}"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"

    - name: configure ssh client - check {{ DEPLOYER_CLI__DST_SSH_KEYS_JUMP_DEST_DIR }} dir exists
      #  check /home/{{DEPLOYER_CLI_USER}}/.ssh/backend_keys dir exists
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_SSH_KEYS_JUMP_DEST_DIR }}"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"

    - name: configure ssh client - check {{ DEPLOYER_CLI__DST_SSH_KEYS_STUDENT_DEST_DIR }} dir exists
      #  check /home/{{DEPLOYER_CLI_USER}}/.ssh/backend_keys dir exists
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_SSH_KEYS_STUDENT_DEST_DIR }}"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"

    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
    # add/inject/create ssh config files in /home/{{DEPLOYER_CLI_USER}}/.ssh/
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    - name: configure ssh client - inject range42 default ssh config in {{ DEPLOYER_CLI__DST_SSH_CONFIG_DEFAULT_FILE }}
      blockinfile:
        path: "{{ DEPLOYER_CLI__DST_SSH_CONFIG_DEFAULT_FILE }}"
        marker: "#### {mark} RANGE42 INCLUDE - {{ INFRASTRUCTURE_CODENAME }} - {{ INFRASTRUCTURE_SCENARIO }} ####"
        block: |

          #### ####  #### #### #### #### #### #### #### #### #### #### #### #### #### ####

          Include {{ DEPLOYER_CLI__DST_SSH_CONFIG_RANGE42_FILE }}

          #### ####  #### #### #### #### #### #### #### #### #### #### #### #### #### ####
        insertafter: EOF

    - name: configure ssh client - inject range42 template ssh config in {{ DEPLOYER_CLI__DST_SSH_CONFIG_RANGE42_FILE }}
      ansible.builtin.template:
        src: remote-deployer-cli.j2
        dest: "{{ DEPLOYER_CLI__DST_SSH_CONFIG_RANGE42_FILE }}"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"

    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
    # add/inject pre-created ssh keys
    #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

    # - name: configure ssh client - copy ssh keys in  {{ DEPLOYER_CLI__DST_SSH_KEYS_BACKEND_DEST_DIR }}
    #   # /home/{{DEPLOYER_CLI_USER}}/.ssh/backend_keys
    #   ansible.builtin.copy:
    #     src: "{{ DEPLOYER_CLI__SRC_GENERATE_KEYS_DIR }}/backend_keys/"
    #     dest: "{{ DEPLOYER_CLI__DST_SSH_KEYS_BACKEND_DEST_DIR }}"
    #     mode: "0600"
    #     directory_mode: "0700"

    # - name: configure ssh client - copy ssh keys in  {{ DEPLOYER_CLI__DST_SSH_KEYS_JUMP_DEST_DIR }}
    #   # /home/{{DEPLOYER_CLI_USER}}/.ssh/backend_keys
    #   ansible.builtin.copy:
    #     src: "{{ DEPLOYER_CLI__SRC_GENERATE_KEYS_DIR }}/jump_keys/"
    #     dest: "{{ DEPLOYER_CLI__DST_SSH_KEYS_JUMP_DEST_DIR }}"
    #     mode: "0600"
    #     directory_mode: "0700"
