---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: configure symlinks - warmup
  block:
    #
    - name: configure symlinks warmup - mkdir -p {{ DEPLOYER_CLI__DST_CONFIG_DIR }}
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0755"
      become: true

- name: configure symlinks - warmup
  block:
    #
    - name: configure symlinks warmup - mkdir -p {{ DEPLOYER_CLI__DST_CONFIG_DIR }}/ssh_keys
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/ssh_keys"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"
      become: true

- name: configure symlinks - warmup
  block:
    #
    - name: configure symlinks warmup - mkdir -p {{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets"
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets"
        state: directory
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0700"
      become: true

- name: configure symlinks
  # become: true
  # become_user: "{{ DEPLOYER_CLI_USER }}"

  block:
    #
    - name: configure symlinks - create secrets symlink to range42-ansible_roles-debug-devkit
      file:
        src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets"
        dest: "{{ DEPLOYER_CLI__DST_GIT_DIR }}/range42-ansible_roles-debug-devkit/secrets"
        state: link
        force: yes

    - name: bug_fix - remove existing demo_lab secrets dir
      file:
        path: "{{ DEPLOYER_CLI__DST_GIT_DIR }}/range42-playbooks/scenarios/demo_lab/secrets"
        state: absent

    - name: configure symlinks - create secrets range42-playbooks/scenarios/demo_lab
      file:
        src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets"
        dest: "{{ DEPLOYER_CLI__DST_GIT_DIR }}/range42-playbooks/scenarios/demo_lab/secrets"
        state: link
        force: yes

    # - name: configure symlinks - create inventory range42-playbooks/scenarios/demo_lab/inventory
    #   file:
    #     src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/inventory"
    #     dest: "{{ DEPLOYER_CLI__DST_GIT_DIR }}/range42-playbooks/scenarios/demo_lab/inventory"
    #     state: link
    #     force: yes
