---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: upload ssh secrets archive - to deployer-cli

  block:
    - name: tarball management -  - create archive (from localhost - {{ INFRASTRUCTURE__AUTO_GENERATED__CONFIG_DIR_LOCAL }}/secrets/ to /tmp/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz ) 
      ansible.builtin.archive:
        path: "{{ INFRASTRUCTURE__AUTO_GENERATED__CONFIG_DIR_LOCAL }}/secrets/"
        # path: "{{ INFRASTRUCTURE__AUTO_GENERATED__ANSIBLE_VAULT_DIR_LOCAL }}/"
        dest: "/tmp/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz"
      delegate_to: localhost
      become: false # we don't want use sudo on localhost.

    - name: tarball management -  upload to remote at /tmp/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz
      ansible.builtin.copy:
        src: "/tmp/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz"
        dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"

    - name: tarball management - extract secrets archive
      ansible.builtin.unarchive:
        src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz"
        dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        remote_src: true

    - name: upload secrets files - add vault utils in {{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/
      ansible.builtin.copy:
        src: "secrets-utils/"
        dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0600"
        directory_mode: "0700"

    # - name: upload secrets files - TEMP PATCH (to delete)
    #   ansible.builtin.copy:
    #     src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/default_vault.yml"
    #     dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/off_cr_42.yml"
    #     remote_src: true
    #     owner: "{{ DEPLOYER_CLI_USER }}"
    #     group: "{{ DEPLOYER_CLI_USER }}"
    #     mode: "0600"

    # - name: upload secrets files - TEMP PATCH (to delete)
    #   ansible.builtin.copy:
    #     src: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/default_vault.yml"
    #     dest: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets/px-testing.cr42_tailscale.yml"
    #     remote_src: true
    #     owner: "{{ DEPLOYER_CLI_USER }}"
    #     group: "{{ DEPLOYER_CLI_USER }}"
    #     mode: "0600"
