services:
  ansible-deployer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: range42/ansible-deployer:latest
    container_name: ansible-deployer
    env_file:
      - .env
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
    tty: true
    stdin_open: true

