
- hosts: range42.ds-px-pub-black-blackwood.deployer-cli
  become: true
  roles:
    - configure.deployer-cli 
  vars:
    DEPLOYER_CLI_USER : "grml"
    INFRASTRUCTURE_CODENAME : "ds-px-pub-black-blackwood"
    INFRASTRUCTURE_SCENARIO : "demo_lab"
    INFRASTRUCTURE_PROXMOX_ADDRESS : "ds-px-pub-black-blackwood.skate-eagle.ts.net"
    INFRASTRUCTURE__AUTO_GENERATED__CONFIG_DIR_LOCAL :  "./config/ds-px-pub-black-blackwood-demo_lab"
    INFRASTRUCTURE__AUTO_GENERATED__SSH_KEYS_DIR_LOCAL : "./config/ds-px-pub-black-blackwood-demo_lab/ssh_keys"
    INFRASTRUCTURE__AUTO_GENERATED__ANSIBLE_VAULT_DIR_LOCAL : "./config/ds-px-pub-black-blackwood-demo_lab/secrets"
    # bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb : "NO"

