---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: systemd-timesyncd task - extra tasks - cover cases =>  vm usage/revert to snapshot
#   block:
#     #
#     - name: remove ntp and ntpdate if present
#       apt:
#         name:
#           - ntp
#           - ntpdate
#         state: absent

#     #
#     - name: check systemd-timesyncd is installed - ubuntu
#       apt:
#         name: systemd-timesyncd
#         state: present

#     #
#     - name: enable and start systemd-timesyncd - ubuntu
#       systemd:
#         name: systemd-timesyncd
#         enabled: true
#         state: started

#   when:
#     - DEV_MODE_INSTALL_JUMP_HOST_ANSIBLE_PACKAGES | default('YES') | upper != 'NO'

#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
#

# - name: install ntp package - time sync - time is now !

#   block:
#     #
#     - name: wait time drift - ubuntu
#       command: timedatectl show -p NTPSynchronized --value
#       register: ntp_sync_check
#       until: ntp_sync_check.stdout == "yes"
#       retries: 10
#       delay: 5
#       changed_when: false

#     #
#     - name: assert - time is sync - ubuntu
#       assert:
#         that:
#           - ntp_sync_check.stdout == "yes"
#         fail_msg: " clock is NOT sync!"
#         success_msg: " clock is sync !"

#   when:
#     - DEV_MODE_INSTALL_JUMP_HOST_ANSIBLE_PACKAGES | default('YES') | upper != 'NO'

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: Update and upgrade system packages
  become: true
  when: DEV_MODE_INSTALL_JUMP_HOST_ANSIBLE_PACKAGES | default('YES') | upper != 'NO'
  block:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true

    - name: Debian/Ubuntu – dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: RHEL/CentOS – upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: Install packages
  become: true
  when: DEV_MODE_INSTALL_JUMP_HOST_ANSIBLE_PACKAGES | upper != 'NO'
  block:

    - name: Install base packages
      ansible.builtin.package:
        name: "{{ configure_deployer_cli_base_packages }}"
        state: present

    - name: Install utils packages
      ansible.builtin.package:
        name: "{{ configure_deployer_cli_utils_packages }}"
        state: present

    - name: Install extra packages
      ansible.builtin.package:
        name: "{{ configure_deployer_cli_extra_packages }}"
        state: present

    - name: Install ansible bootstrap packages per OS family
      ansible.builtin.package:
        name: "{{ configure_deployer_cli_ansible_packages[ansible_facts['os_family']] }}"
        state: present
      when: ansible_facts['os_family'] in configure_deployer_cli_ansible_packages

    # ###############################################
    #
    # NOTE THE FOLLOWING WILL NOT ALWAYS WORK
    #
    # - name: install packages - install ansible
    #   apt:
    #     name:
    #       - ansible
    #     state: present
    #
    # ###############################################
    # Fix :
    #
    #   The following task will NOT call apt-mark that can cause issue during
    #   installation on remote system without ansible
    #
    #
    # - name: install packages - install ansible - bootstrapping
    #   ansible.builtin.raw: |
    #     apt-get update -y
    #     apt-get install -y python3 ansible

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

# - name: basics configuration - check en_US.UTF-8 locale exists
#   community.general.locale_gen:
#     name: en_US.UTF-8
#     state: present

# - name: basic configuration - set default locale to en_US.UTF-8
#   ansible.builtin.lineinfile:
#     path: /etc/default/locale
#     regexp: "^LANG="
#     line: "LANG=en_US.UTF-8"

#   when:
#     - DEV_MODE_INSTALL_JUMP_HOST_ANSIBLE_PACKAGES | default('YES') | upper != 'NO'

#
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####
