---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: configure dotfiles for "{{ DEPLOYER_CLI_USER }}"
  # become: true
  # become_user: "{{ DEPLOYER_CLI_USER }}"

  block:
    - name: configure dotfile - copy vimrc - for [ "{{ DEPLOYER_CLI_USER }}" ]
      ansible.builtin.copy:
        src: dot_files/vimrc
        dest: "/home/{{ DEPLOYER_CLI_USER }}/.vimrc"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0644"

    - name: configure dotfile - copy zshrc - for [ "{{ DEPLOYER_CLI_USER }}" ]
      ansible.builtin.copy:
        src: dot_files/zshrc
        dest: "/home/{{ DEPLOYER_CLI_USER }}/.zshrc"
        owner: "{{ DEPLOYER_CLI_USER }}"
        group: "{{ DEPLOYER_CLI_USER }}"
        mode: "0644"

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: configure dotfiles for [ root ]

  block:
    - name: configure dotfile - copy vimrc - for [ root ]
      ansible.builtin.copy:
        src: dot_files/vimrc
        dest: "/root/vimrc"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: configure dotfile - copy zshrc - for [ root ]
      ansible.builtin.copy:
        src: dot_files/zshrc
        dest: "/home/{{ DEPLOYER_CLI_USER }}/.zshrc"
        owner: "root"
        group: "root"
        mode: "0644"
