---
#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### ####

- name: clean up secrets files
  block:
    - name: clean up secrets files - remove archive
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets-{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}.tar.gz"
        state: absent

    - name: clean up secrets files - remove vault_pass.txt
      ansible.builtin.file:
        path: "{{ DEPLOYER_CLI__DST_CONFIG_DIR }}/secrets-{{ INFRASTRUCTURE_CODENAME }}/secrets/vault_pass.txt"
        state: absent

  when: clean_up_secret | default('NO') | upper == 'YES'
