---
- name: APT MIRROR CONFIGURE - UPDATE APT CACHE (AIRGAPPED)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: APT MIRROR CONFIGURE - INSTALL APT-MIRROR AND NGINX
  ansible.builtin.apt:
    name:
      - apt-mirror
      - nginx
    state: present
