- name: "Check if we should generate VM passwords"
  ansible.builtin.set_fact:
    generate_vm_passwords: "{{ context_auto_generate_vm_passwords | default('YES') | upper == 'YES' }}"

- name: "Generate VM passwords"
  ansible.builtin.set_fact:
    INFRASTRUCTURE_DEFAULT_ADMIN_VM_CI_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    INFRASTRUCTURE_DEFAULT_TRAINEE_VM_CI_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    INFRASTRUCTURE_WAZUH_ADMIN_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
  when: generate_vm_passwords

- name: "Use existing passwords from config if generation disabled"
  ansible.builtin.set_fact:
    INFRASTRUCTURE_DEFAULT_ADMIN_VM_CI_PASSWORD: "{{ default_admin_vm_ci_password }}"
    INFRASTRUCTURE_DEFAULT_TRAINEE_VM_CI_PASSWORD: "{{ default_trainee_vm_ci_password }}"
    INFRASTRUCTURE_WAZUH_ADMIN_PASSWORD: "{{ WAZUH_PASSWORD }}"
  when: not generate_vm_passwords

- name: "Printing generated passwords"
  ansible.builtin.debug:
    msg:
      - "Admin VM password: {{ INFRASTRUCTURE_DEFAULT_ADMIN_VM_CI_PASSWORD }}"
      - "Trainee VM password: {{ INFRASTRUCTURE_DEFAULT_TRAINEE_VM_CI_PASSWORD }}"
      - "Wazuh password: {{ INFRASTRUCTURE_WAZUH_ADMIN_PASSWORD }}"