- name: Show deployer mode
  ansible.builtin.debug:
    msg: "Running deployer in {{ deployer_mode }} mode"

- name: "Prepare environment passwords"
  ansible.builtin.import_tasks: generate_passwords.yml

- name: "Prepare SSH key directories"
  ansible.builtin.import_tasks: ssh_keys_dirs.yml

- name: "Generate SSH keys"
  ansible.builtin.import_tasks: ssh_keys_generate.yml

- name: "Write passwords/passphrases file"
  ansible.builtin.import_tasks: ssh_keys_summary.yml

- name: Run local deployer tasks
  ansible.builtin.import_tasks: local.yml
  when: deployer_is_local

- name: Run remote deployer tasks
  ansible.builtin.import_tasks: remote.yml
  when: deployer_is_remote
