- name: "Check if we should generate SSH keys"
  ansible.builtin.set_fact:
    generate_ssh_keys: "{{ context_auto_generate_ssh_keys | default('YES') | upper == 'YES' }}"

- name: "Generate SSH key passwords"
  ansible.builtin.set_fact:
    PX_ROOT_PASSPHRASE: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    PX_JUMP_PASSPHRASE: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    DEPLOYER_PASSPHRASE: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    STUDENT_PASSPHRASE: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    ALICE_USER_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    BOB_USER_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
  when: generate_ssh_keys

- name: "Print generated passphrase and password"
  ansible.builtin.debug:
    msg:
      - "Proxmox SSH key root passphrase: {{ PX_ROOT_PASSPHRASE }}"
      - "Proxmox SSH key jump passphrase: {{ PX_JUMP_PASSPHRASE }}"
      - "Deployer SSH key passphrase: {{ DEPLOYER_PASSPHRASE }}"
      - "Alice user password: {{ ALICE_USER_PASSWORD }}"
      - "Bob user password: {{ BOB_USER_PASSWORD }}"

- name: "Generate Proxmox root SSH key"
  community.crypto.openssh_keypair:
    path: "{{ deployer_infrastructure_ssh_keys_dir_local }}/jump_keys/px.{{ infrastructure_codename }}-{{ infrastructure_scenario }}-ssh_cli.root"
    type: ed25519
    size: 4096
    passphrase: "{{ PX_ROOT_PASSPHRASE | default(omit) }}"
    regenerate: full_idempotence
  register: px_root_key
  when: generate_ssh_keys

- name: "Generate Proxmox jump SSH key"
  community.crypto.openssh_keypair:
    path: "{{ deployer_infrastructure_ssh_keys_dir_local }}/jump_keys/px.{{ infrastructure_codename }}-{{ infrastructure_scenario }}-ssh_cli.jump_user"
    type: ed25519
    size: 4096
    passphrase: "{{ PX_JUMP_PASSPHRASE | default(omit) }}"
    regenerate: full_idempotence
  register: px_jump_key
  when: generate_ssh_keys

- name: "Generate deployer (Alice) SSH key"
  community.crypto.openssh_keypair:
    path: "{{ deployer_infrastructure_ssh_keys_dir_local }}/backend_keys/r42.{{ infrastructure_codename }}-{{ infrastructure_scenario }}-deployer-key_alice"
    type: ed25519
    size: 4096
    passphrase: "{{ DEPLOYER_PASSPHRASE | default(omit) }}"
    regenerate: full_idempotence
  register: deployer_key
  when: generate_ssh_keys

- name: "Generate student (Bob) SSH key"
  community.crypto.openssh_keypair:
    path: "{{ deployer_infrastructure_ssh_keys_dir_local }}/student_keys/r42.{{ infrastructure_codename }}-{{ infrastructure_scenario }}-student-key_bob"
    type: ed25519
    size: 4096
    passphrase: "{{ STUDENT_PASSPHRASE | default(omit) }}"
    regenerate: full_idempotence
  register: student_key
  when: generate_ssh_keys

- name: "Generate additional student keys"
  community.crypto.openssh_keypair:
    path: "{{ deployer_infrastructure_ssh_keys_dir_local }}/student_keys/additionnal_students/r42.{{ infrastructure_codename }}-{{ infrastructure_scenario }}-student-key_bob_{{ item }}"
    type: ed25519
    size: 4096
    passphrase: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
    regenerate: full_idempotence
  loop: "{{ range(1, student_additionnal_keys_count + 1) | list }}"
  when: generate_ssh_keys
