


OPERATOR_USER: "range42-operator"

SSH_CONFIG_DIR: "/home/{{OPERATOR_USER}}/.ssh"
SSH_CONFIG_DEFAULT_FILE: "{{ SSH_CONFIG_DIR }}/config"
SSH_CONFIG_CR42_FILE: "{{ SSH_CONFIG_DIR }}/config_CR42"

SRC_KEYS_DIR: "ssh_keys/" # files/ssh_keys

RANGE_42_GIT_DIR: "/home/{{OPERATOR_USER}}/CR42"
RANGE_42_CONFIG_DIR: "/home/{{OPERATOR_USER}}/CR42.config"
RANGE_42_PROXMOX_REMOTE_HOST: "FQDN_OR_IP_TO_DEFINE"

RANGE_42_SSH_KEYS_BACKEND_DEST_DIR: "{{ SSH_CONFIG_DIR }}/backend_keys"
RANGE_42_SSH_KEYS_JUMP_DEST_DIR: "{{ SSH_CONFIG_DIR }}/jump_keys"